# ----- Crypto Movez www.cryptomovez.com -----

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"

ACCOUNTS=[ "GDP4DU3CVYRMOK4OM2ARAG43RYB4NVGGVXUH2A2BPI4FSEPPBW5EM5AQ", "GDBUGGBX52VA2SOVKPVWKCN55YU2VKWS2G6XRP4NMKQLVYBKDF2VTB4J", "GDXD6454BB3FFAJSL3CL3AFXF6TD4ETPH6XWXM6WBI3OSPLHXO3L2GW4" ]

[DOCUMENTATION]
ORG_NAME="Crypto Movez"<
ORG_DBA="Crypto Movez LLC"
ORG_PHYSICAL_ADDRESS="573 Enfield Drive Frisco, TX 75036, United States"
ORG_PHONE_NUMBER="1 (469)-556-4000"
ORG_URL="https://www.cryptomovez.com"
ORG_LOGO="https://cryptomovez.com/assets/CM_logo_white.png"
ORG_DESCRIPTION="Testing"
ORG_OFFICIAL_EMAIL="corey@cryptocorey.com"

[[PRINCIPALS]]
name="Corey Michael Chadwick"
email="corey@cryptocorey.com"
github="teamonepercent"

[[CURRENCIES]]
code="movez"
issuer="GDP4DU3CVYRMOK4OM2ARAG43RYB4NVGGVXUH2A2BPI4FSEPPBW5EM5AQ"
display_decimals=2
anchor_asset_type="crypto"
anchor_asset="XLM"
name="crypto movez"
desc="test"
image="https://cryptomovez.com/assets/CM_logo_white.png"
